version: "3.8"

services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USERNAME=${SPLUNK_USERNAME}
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
    ports:
      - "8001:8000"
      - "8089:8089"
    volumes:
      - splunk-data:/opt/splunk/var

volumes:
  splunk-data:
